### ISSUE TITLE
Error installing PyAudio

### ISSUE THREAD

**Issue by IanUmney** [king-technologies/virtual-assistant#2]
I tried installing PyAudio and received this error (pictured).

![PyAudio_Error](https://user-images.githubusercontent.com/25939118/121769143-9dd6bd00-cb6a-11eb-966b-f746624638a7.png)

**Comment by Rohit19060** [comment]
This issue is not in The Assistant it's in PyAudio Installation, Have you Tried PyAudio Team?

**Comment by IanUmney** [comment]
I managed to work around the problem, I think by installing pyaudio from source if I remember.
